version: '3.1'

networks:
  temperature_monitoring_net:
    driver: bridge

volumes:
  maven-cache:
    driver: local

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.backend
    container_name: temperature-processing-api
    image: s7thiago/temperature-processing-api:latest
    networks:
      - temperature_monitoring_net
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ../:/workspace # Montar o código para desenvolvimento no container
      - maven-cache:/root/.m2 # Cache do maven para não baixar as dependências toda vez
      # - ./root-data:/root/ # volume para o .zshrc
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: ["sh", "-c", "trap 'docker-compose stop' EXIT; while :; do sleep 1; done"] # Manter o container em execução
