version: '3.1'

networks:
  temperature_monitoring_net:
    driver: bridge

volumes:
  maven-cache:
    driver: local
  gradle-cache:  # NOVO: Cache do Gradle
    driver: local
  vscode-extensions:  # NOVO: Cache das extensões VS Code
    driver: local
  gradle-wrapper-cache:  # NOVO: Cache do Gradle Wrapper
    driver: local

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.backend
    container_name: temperature-processing-api
    image: s7thiago/temperature-processing-api:latest
    networks:
      - temperature_monitoring_net
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ../:/workspace
      - maven-cache:/root/.m2
      # NOVOS VOLUMES para cache
      - gradle-cache:/root/.gradle  # Cache principal do Gradle
      - gradle-wrapper-cache:/root/.gradle/wrapper  # Cache do wrapper
      - vscode-extensions:/root/.vscode-server  # Extensions do VS Code
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command: ["sh", "-c", "trap 'docker-compose stop' EXIT; while :; do sleep 1; done"]